### ISSUE TITLE
Missing access token when creating GraphQL client

### ISSUE THREAD

**Issue by PurplePineapple123** [fotimo/shopify-auth#1]
I implemented `customSessionStorage` as outlined (for postgres) and it works in adding all data to the database. Console logs in `loadCallback` show that the correct data is being returned. Additionally, the app works with `MemorySessionStorage`. 

However, as the app is trying to load and all the data has been added to the database, the server crashes with the following error: 
`InternalServerError: Missing access token when creating GraphQL client`.

Have you seen this before? Not sure why this would be occurring as all online and offline tokens are created and available.

Edit: Looks like the offline access token is never created in the database and `const { shop, accessToken, scope } = ctx.state.shopify; ` returns undefined. Digging deeper.

**Comment by fotimo** [comment]
Hi, please check if the first step of the app installation / auth process has been completed.

1.Step:
ctx.redirect(`/install/auth?shop=${shop}`);

```JavaScript
// shopify auth - offline accessMode for offline token
server.use(
    createShopifyAuth({
        accessMode: "offline",
        prefix: "/install",
        async afterAuth(ctx) {
            const {
                shop,
                accessToken,
                scope,
            } = ctx.state.shopify;

            // set shopify offline token to database
            await setOfflineAccessToken(shop, accessToken)

            // redirect to shopify auth - online accessMode
            ctx.redirect(`/auth?shop=${shop}`)
        },
    }),
);
```
