### ISSUE TITLE
Accessing Offline Access Token 

### ISSUE THREAD

**Issue by PurplePineapple123** [fotimo/shopify-auth#2]
With this oAuth implementation, once you set the offline access token with `setOfflineAccessToken`, are you still able to create an offline session using `loadOfflineSession(shop)` and if not, how are you creating an offline session? 

I could just make a database call directly and pull the `offline_access_token`, but I just wasn't sure if there was a way to use the `loadOfflineSession(shop)` method. 

I ask because our app has a check to during oauth to make sure the token is able to access the Admin api: 

```
 try {
        const session = await Shopify.Utils.loadOfflineSession(shop);
         //loading current session returns undefined for some reason. Currently debugging and would rather use 
         //loadCurrentSession vs loadOfflineSession
         //const session = await Shopify.Utils.loadCurrentSession(ctx.req, ctx.res)

        
       const client = new Shopify.Clients.Rest(
          session.shop,
          session.accessToken
        );

        const data = await client.get({
          path: "orders",
          query: { status: "any", limit: 1 },
        });

        const scope = await pool.query(
          `SELECT scope FROM shop WHERE shop_url=$1`,
          [shop]
        );

        ACTIVE_SHOPIFY_SHOPS[shop] = scope.rows[0].scope;

      } catch (error) {
        console.log(error);
        ACTIVE_SHOPIFY_SHOPS[shop] = undefined;
      }
    } else {
      ACTIVE_SHOPIFY_SHOPS[shop] = undefined;
    }

if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
      ctx.redirect(`/offline/auth?shop=${shop}`);
      return;
    }

```
Since the offline session is being created, and the offline token never expires, it shouldn't force an oAuth redirect after 24 hours if the store exists. However, if the users logs back into the app after 24 hours, then the following code says the token is expired and forces the oAuth redirect again. This leads me to believe that `loadCurrentSession` doesn't pull the offline access token with this implementation. 

```
const client = new Shopify.Clients.Rest(
          session.shop,
          session.accessToken
        );
```

**Comment by fotimo** [comment]
@PurplePineapple123 
The offline session token is valid as long as the app is installed. All the information you need to get from the `const session = await Shopify.Utils.loadOfflineSession(shop);` you surely have in your database, right? In my case, this was the case. This makes it possible to process all Shopify API requests with this data from the database.

**Comment by PurplePineapple123** [comment]
@fotimo, thanks for the reply! Correct, all the needed data is stored in the database. I can easily make a get request to the database for the offline token and then just use that. Really, I was just verifying that the `loadOfflineSession(shop)` function doesn't work  and just making a direct database call is the correct way to go. That's what I'm going to do, thanks for the help :)

**Comment by fotimo** [comment]
> @fotimo, thanks for the reply! Correct, all the needed data is stored in the database. I can easily make a get request to the database for the offline token and then just use that. Really, I was just verifying that the `loadOfflineSession(shop)` function doesn't work  and just making a direct database call is the correct way to go. That's what I'm going to do, thanks for the help :)

Cheers Mate! Have nice Weekend.
